package com.example.appdblibrary.entity.enums;

public enum Permissions {

    ADD_CATEGORY,
    ADD_PERMISSIONS_ROLE,
    ADD_PRODUCT,
    ADD_ROLE,
    ADD_FAVOURITE,
    ADD_SALE,
    ADD_RECOMMENDED_PRODUCT,

    DELETE_CATEGORY,
    DELETE_PERMISSIONS_ROLE,
    DELETE_PRODUCT,
    DELETE_ROLE,
    DELETE_SALE,
    DELETE_USER,
    DELETE_RECOMMENDED_PRODUCT,

    DOWNLOAD_ATTACHMENT,
    EDIT_CATEGORY,
    EDIT_PRODUCT,
    EDIT_ROLE,
    EDIT_USER,
    EDIT_SALE,
    EDIT_RECOMMENDED_PRODUCT,

    MANAGE_ROLE_TO_USER,
    UPLOAD_ATTACHMENT,
    VIEW_CATEGORY,
    VIEW_PRODUCT,
    VIEW_RECOMMENDED_PRODUCT,
    VIEW_ROLE,
    VIEW_USER,
    VIEW_SALE,

    ;

}
